--- # My First Playbook

- hosts: webhosts
  user: test
  sudo: yes
  connection: ssh
  gather_facts: no
  vars:
   playbook_version: 0.1v
  vars_files:
   - conf/copyright.yml
   - conf/webdefaults.yml
  tasks:
   - name: Install Apache Web Server
     action: apt name=apache2 state=installed
   - name: Verify the lynx Web browser
     action: apt name=lynx state=present
